name: 'Generate Changelog (Conventional Commit)'
description: 'Generate a changelog from given tag references'
author: 'Seasonal Matcha <seasonalmatcha@gmail.com>'
branding:
  icon: 'file-plus'
  color: 'blue'
inputs:
  from:
    description: 'Tag name or reference for the starting point'
    required: true
  to:
    description: 'Tag name or reference for the ending'
    required: true
  config-file:
    description: 'Path to custom config file'
    required: false
outputs:
  changelog:
    description: 'Changelog in markdown format'
runs:
  using: 'node12'
  main: 'dist/index.js'
